"""Shared vocabulary for vendor configuration generators.

Every vendor names the same algorithm differently, and the translation is where a
remediation document quietly becomes wrong. ``aes256gcm16`` is ``aes_gcm256`` to
Libreswan, ``aes-gcm-256`` to Cisco, ``aes256gcm`` to FortiGate and ``aes-256-gcm`` to
Juniper — and a generator that guesses produces a file the operator pastes in, which the
device rejects at 2 a.m. So the mappings are explicit tables, one per vendor, and a
missing entry raises rather than falling back to the canonical name.

**Deployment status is part of the output, not a footnote.** Only strongSwan is proven
against a live tunnel in this testbed. Every other generator is syntax-validated against
the vendor's documented grammar and nothing more, and each emitted document says so in
its own header. A vendor configuration that has never been loaded onto that vendor's
device is a plausible-looking draft, and presenting it with the same confidence as one
that established a real tunnel would be the most damaging kind of overclaim this project
could make.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Final, Protocol, runtime_checkable

from ipsec_sentinel.remediate.models import ChangePackage
from testbed.orchestrate.config_gen import TunnelConfig


class DeploymentStatus(StrEnum):
    """How far a generator's output has actually been proven."""

    LIVE_TESTED = "live-tested"
    """Loaded onto a real device in this project's testbed; a tunnel established."""

    SYNTAX_VALIDATED = "syntax-validated, not deployment-tested"
    """Checked against the vendor's documented grammar. Never loaded onto a device."""


class UnsupportedAlgorithmError(ValueError):
    """The vendor has no name for an algorithm, or the mapping is missing one.

    Raised rather than defaulted. A generator that emits the canonical name when it
    cannot translate produces a file that looks right and is rejected by the device.
    """


@runtime_checkable
class VendorGenerator(Protocol):
    """What every vendor generator provides."""

    vendor: str
    filename: str
    status: DeploymentStatus

    def render(self, config: TunnelConfig, role: str) -> str: ...


def translate(table: dict[str, str], value: str, kind: str, vendor: str) -> str:
    """Look up a vendor's name for a canonical algorithm, or refuse."""
    if value not in table:
        raise UnsupportedAlgorithmError(
            f"{vendor} has no mapping for {kind} {value!r}; supported: "
            f"{sorted(table)}. Emitting the canonical name would produce a file the "
            f"device rejects."
        )
    return table[value]


def status_banner(vendor: str, status: DeploymentStatus, comment: str = "#") -> str:
    """The header every generated document carries.

    Written into the configuration itself rather than only into a report, because the
    file is what gets pasted into a change ticket, and the caveat has to travel with it.
    """
    lines = [
        f"{comment} Generated by IPsec Sentinel for {vendor}.",
        f"{comment} Status: {status.value}.",
    ]
    if status is DeploymentStatus.SYNTAX_VALIDATED:
        lines += [
            f"{comment}",
            f"{comment} This configuration has NOT been loaded onto a {vendor} device.",
            f"{comment} It is generated from the documented grammar and checked against",
            f"{comment} it, which is not the same as knowing the device accepts it.",
            f"{comment} Review it before applying, and apply it in a maintenance window.",
        ]
    else:
        lines += [
            f"{comment}",
            f"{comment} This configuration form was loaded onto a live {vendor} instance",
            f"{comment} in the project's testbed and established a tunnel carrying ESP.",
        ]
    lines += [
        f"{comment}",
        f"{comment} Apply this yourself. This tool never writes to a device.",
    ]
    return "\n".join(lines)


def both_ends(generator: VendorGenerator, config: TunnelConfig) -> tuple[str, str]:
    """Render both ends, because one end alone is not a change."""
    return generator.render(config, "left"), generator.render(config, "right")


def describe_package_status(package: ChangePackage) -> str:
    """The status line a report shows beside a change package."""
    return f"{package.local_config.vendor}: {package.tunnel_id}"


# Canonical names, from testbed/configs/matrix.yaml. Every vendor table below must
# cover these or raise on the gap.
CANONICAL_ENCRYPTIONS: Final[frozenset[str]] = frozenset(
    {"aes256gcm16", "aes128gcm16", "aes256", "aes128", "3des"}
)
CANONICAL_INTEGRITIES: Final[frozenset[str]] = frozenset({"sha256", "sha384", "sha1", "md5"})
CANONICAL_DH_GROUPS: Final[frozenset[str]] = frozenset(
    {"modp1024", "modp1536", "modp2048", "ecp256", "ecp384", "curve25519"}
)
