"""VoIP traffic generator.

The most distinctive shape in the corpus: small, near-constant-size packets arriving
on a metronome, symmetric in both directions. It is also the clearest demonstration of
what the ML lane is for, because none of it is readable through ESP — only the rhythm
survives encryption.

Codec choice is the point of the variants. G.711 packetises 20 ms as 160 bytes of
media; G.729 packetises the same 20 ms as 20 bytes. Same interval, an eightfold
difference in size, so a classifier that has learned "VoIP means 172-byte packets"
rather than "VoIP means a metronome" will fail on G.729 and the confusion matrix will
say so.

**Disclosure:** this drives a synthetic RTP endpoint, not a softphone. There is no SIP
signalling and no real codec; the media payload is generated bytes. Packet timing and
size distribution are faithful, and through an ESP tunnel those are the only
observable properties — but the limitation is recorded in docs/DATASET.md rather than
implied away.
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from datetime import UTC, datetime
from typing import ClassVar, Final

from testbed.traffic.base import GenerationResult, RunContext

RTP_ENDPOINT: Final = "/opt/sentinel/rtp_endpoint.py"
RTP_HEADER_BYTES: Final = 12
IP_UDP_OVERHEAD_BYTES: Final = 28


@dataclass(frozen=True)
class VoipVariant:
    """One codec's packetisation: how often, and how much media per packet."""

    name: str
    codec: str
    interval_ms: float
    media_bytes: int

    @property
    def wire_bytes(self) -> int:
        """Bytes on the wire per packet, before ESP encapsulation."""
        return self.media_bytes + RTP_HEADER_BYTES + IP_UDP_OVERHEAD_BYTES


VARIANTS: Final[dict[str, VoipVariant]] = {
    "g711_20ms": VoipVariant("g711_20ms", codec="g711", interval_ms=20.0, media_bytes=160),
    "g729_20ms": VoipVariant("g729_20ms", codec="g729", interval_ms=20.0, media_bytes=20),
}

LEFT_PORT: Final = 40000
RIGHT_PORT: Final = 40002


class VoipGenerator:
    """Run a bidirectional RTP stream between the two hosts."""

    name = "voip"
    requires: ClassVar[list[str]] = []

    def __init__(self, variant: str = "g711_20ms") -> None:
        if variant not in VARIANTS:
            raise ValueError(f"unknown VoIP variant {variant!r}; have {sorted(VARIANTS)}")
        self.variant = VARIANTS[variant]
        self._ctx: RunContext | None = None

    def setup(self, ctx: RunContext) -> None:
        self._ctx = ctx

    def teardown(self) -> None:
        self._ctx = None

    def expected_packets(self, duration_s: int) -> int:
        """Packets one direction should emit over ``duration_s``."""
        return int(duration_s * 1000 / self.variant.interval_ms)

    def _endpoint_argv(
        self, container: str, peer_ip: str, local_port: int, peer_port: int, duration_s: int
    ) -> list[str]:
        return [
            "docker",
            "exec",
            container,
            "python3",
            RTP_ENDPOINT,
            "--peer",
            peer_ip,
            "--local-port",
            str(local_port),
            "--peer-port",
            str(peer_port),
            "--codec",
            self.variant.codec,
            "--interval-ms",
            str(self.variant.interval_ms),
            "--duration-s",
            str(duration_s),
        ]

    def run(self, duration_s: int) -> GenerationResult:
        if self._ctx is None:
            raise RuntimeError("setup() must be called before run()")
        ctx = self._ctx

        started = datetime.now(UTC)
        # Both endpoints run concurrently; a call is symmetric by nature, and starting
        # them sequentially would make the first half of the capture one-directional.
        right = subprocess.Popen(
            self._endpoint_argv(
                ctx.right_host, ctx.left_host_ip, RIGHT_PORT, LEFT_PORT, duration_s
            ),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        left = subprocess.Popen(
            self._endpoint_argv(
                ctx.left_host, ctx.right_host_ip, LEFT_PORT, RIGHT_PORT, duration_s
            ),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        try:
            left_out, left_err = left.communicate(timeout=duration_s + 60)
            right_out, right_err = right.communicate(timeout=duration_s + 60)
        except subprocess.TimeoutExpired:
            left.kill()
            right.kill()
            ended = datetime.now(UTC)
            return GenerationResult(
                generator=self.name,
                variant=self.variant.name,
                packets_sent=0,
                bytes_sent=0,
                started_at=started,
                ended_at=ended,
                success=False,
                error="RTP endpoints did not exit within the timeout",
            )
        ended = datetime.now(UTC)

        sent = _parse_sent(left_out) + _parse_sent(right_out)
        if sent == 0:
            detail = (left_err or right_err or left_out or right_out).strip()[:200]
            return GenerationResult(
                generator=self.name,
                variant=self.variant.name,
                packets_sent=0,
                bytes_sent=0,
                started_at=started,
                ended_at=ended,
                success=False,
                error=f"RTP endpoints sent no packets: {detail}",
            )
        return GenerationResult(
            generator=self.name,
            variant=self.variant.name,
            packets_sent=sent,
            bytes_sent=sent * self.variant.wire_bytes,
            started_at=started,
            ended_at=ended,
            success=True,
        )


def _parse_sent(output: str) -> int:
    """Read ``sent=<n>`` from an endpoint's summary line."""
    for token in output.split():
        if token.startswith("sent="):
            try:
                return int(token.split("=", 1)[1])
            except ValueError:
                return 0
    return 0
