"""Machine-readable export, and the schema that makes it a contract.

The HTML report is for a person. This is for whatever comes next — a SIEM, a ticketing
system, a later run of this tool comparing against an earlier one. That means the shape
has to be *promised*, not merely produced, so the schema is generated from the model and
written to a file that is checked in and tested against. A schema nothing validates
against is documentation; a schema the tests enforce is a contract.

Round-tripping is part of that contract and is tested both ways: a report exported and
re-loaded must equal the original, and an export must validate against the published
schema. The second catches the case the first cannot — a change that is internally
consistent but silently alters the shape every downstream consumer reads.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Final

from ipsec_sentinel.report.models import SCHEMA_VERSION, Report

SCHEMA_DIR: Final = Path(__file__).resolve().parents[3] / "schemas"
SCHEMA_FILENAME: Final = f"report-{SCHEMA_VERSION}.schema.json"
SCHEMA_ID: Final = f"https://ipsec-sentinel.invalid/schemas/{SCHEMA_FILENAME}"
INDENT: Final = 2


def report_schema() -> dict[str, Any]:
    """The JSON Schema for a report, generated from the model itself.

    Generated rather than hand-written, so the schema cannot drift from the thing it
    describes. The identifier is a ``.invalid`` host on purpose: it names the schema
    without implying that anything will be fetched from it, and nothing in this tool
    resolves it.
    """
    schema = Report.model_json_schema(mode="serialization")
    schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
    schema["$id"] = SCHEMA_ID
    schema["title"] = f"IPsec Sentinel report {SCHEMA_VERSION}"
    return schema


def schema_path() -> Path:
    return SCHEMA_DIR / SCHEMA_FILENAME


def write_schema(destination: Path | None = None) -> Path:
    """Write the published schema. Regenerated by a test so it cannot go stale."""
    target = destination or schema_path()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(_dump(report_schema()), encoding="utf-8")
    return target


def export_json(report: Report) -> str:
    """The report as JSON text, stable enough to diff between runs.

    Keys are not sorted: the model's field order is meaningful — metadata, then the
    summary, then Section A before Section B — and alphabetising it would put
    ``section_b_inferred`` before ``section_a_verified`` in every export, which is a
    small thing that undermines the one distinction the document exists to make.
    """
    return _dump(json.loads(report.model_dump_json()))


def _dump(payload: Any) -> str:
    return json.dumps(payload, indent=INDENT, ensure_ascii=False) + "\n"


def write_json(report: Report, destination: Path) -> Path:
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(export_json(report), encoding="utf-8")
    return destination


def load_report(text: str) -> Report:
    """Read a report back. Unknown fields are refused, not dropped.

    A future export loaded by an older build fails loudly here rather than validating
    with parts of it quietly missing, which is the difference between an incompatibility
    and silent data loss.
    """
    return Report.model_validate_json(text)
