"""Generate ``docs/COMPLIANCE_BASELINES.md`` from the baseline definitions.

The same discipline as ``generate_rules_doc.py``, and for the same reason: a hand-written
table of what six standards require drifts from the YAML that actually decides, and the
drift is invisible until somebody relies on it.

The column that matters most is **verified**. Two of the six baselines were encoded from
public descriptions rather than from a controlling document, because those documents are
not freely redistributable. Each carries a ``provenance`` paragraph saying so, and this
document reproduces it rather than summarising it — a caveat that survives only in a YAML
comment is a caveat nobody reads.

    python -m scripts.generate_baselines_doc          # writes the document
    python -m scripts.generate_baselines_doc --check  # exits non-zero if it is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Final

from ipsec_sentinel.assess.baselines.schema import get_baseline, load_baselines
from ipsec_sentinel.assess.framework import BUILTIN_TAGS
from ipsec_sentinel.assess.rules import default_registry

REPO_ROOT: Final = Path(__file__).resolve().parents[1]
DESTINATION: Final = REPO_ROOT / "docs" / "COMPLIANCE_BASELINES.md"

MINIMUMS: Final = (
    ("encryption_key_bits", "Minimum symmetric key", "bits"),
    ("dh_security_bits", "Minimum DH security strength", "bits"),
    ("ike_lifetime_seconds", "Maximum IKE SA lifetime", "s"),
    ("child_lifetime_seconds", "Maximum child SA lifetime", "s"),
    ("replay_window", "Minimum anti-replay window", "packets"),
)


def paragraph(text: str | None) -> str:
    """Collapse a YAML folded block into one paragraph."""
    return " ".join((text or "").split())


def render_baselines_document() -> str:
    names = sorted(load_baselines())
    baselines = {name: get_baseline(name) for name in names}
    total_rules = len(default_registry().rules)

    lines: list[str] = [
        "# Compliance baselines",
        "",
        "<!-- Generated by scripts/generate_baselines_doc.py. Do not edit by hand: a test",
        "     regenerates this file and fails if it has drifted from the definitions. -->",
        "",
        f"**{len(names)} published baselines** and **{len(BUILTIN_TAGS)} built-in tags**, "
        f"selecting from {total_rules} rules.",
        "",
        "A baseline is a policy document expressed as a rule selection and a set of",
        "thresholds. Running the same capture under two of them produces two different",
        "reports from one parse, because the parse is a fact and the judgement is a policy.",
        "",
        "> For what each rule actually checks, see [RULES.md](RULES.md). For the ML baselines",
        "> the models have to beat — a different sense of the word entirely — see",
        "> [BASELINES.md](BASELINES.md).",
        "",
        "## The two namespaces",
        "",
        "`default` and `strict` are **tags** written on the rules themselves. Everything",
        "else is the **id of a published baseline**, which selects rules by listing their",
        "IDs and is authoritative over a rule's own tag list.",
        "",
        "Conflating them is not hypothetical: it made a named baseline silently select zero",
        "rules and grade every capture A, and the test that should have caught it asserted",
        "the broken behaviour. `RuleRegistry.resolve` now raises `UnknownBaselineError`",
        "rather than running an empty rule set.",
        "",
        "## At a glance",
        "",
        "| Baseline | Authority | Rules | Verified against source |",
        "|---|---|---|---|",
    ]
    for name in names:
        baseline = baselines[name]
        mark = "yes" if baseline.verified else "**no — see below**"
        lines.append(
            f"| `{name}` | {baseline.authority} | {len(baseline.rules)}/{total_rules} | {mark} |"
        )

    lines += [
        "",
        "## Thresholds",
        "",
        "Where a baseline states no threshold the cell is `—`, and the corresponding rule",
        "does not run under it. That is different from a threshold of zero.",
        "",
        "| Requirement | " + " | ".join(f"`{name}`" for name in names) + " |",
        "|---" * (len(names) + 1) + "|",
    ]
    for attribute, label, unit in MINIMUMS:
        cells = []
        for name in names:
            value = getattr(baselines[name].minimums, attribute, None)
            cells.append("—" if value is None else f"{value} {unit}")
        lines.append(f"| {label} | " + " | ".join(cells) + " |")

    for attribute, label in (
        ("require_pfs", "Requires forward secrecy"),
        ("require_post_quantum", "Requires post-quantum key exchange"),
    ):
        cells = []
        for name in names:
            value = getattr(baselines[name].minimums, attribute, None)
            cells.append("—" if value is None else ("yes" if value else "no"))
        lines.append(f"| {label} | " + " | ".join(cells) + " |")
    lines.append("")

    for name in names:
        baseline = baselines[name]
        lines += [
            f"## {baseline.name}",
            "",
            f"- **id** `{name}`",
            f"- **authority** {baseline.authority}",
            f"- **reference** {paragraph(baseline.reference)}",
            f"- **rules selected** {len(baseline.rules)} of {total_rules}",
            "",
            paragraph(baseline.description),
            "",
        ]
        if baseline.severity_overrides:
            lines += [
                "This baseline disagrees with the default severity of some rules:",
                "",
                "| Rule | Severity under this baseline |",
                "|---|---|",
            ]
            for rule_id, severity in sorted(baseline.severity_overrides.items()):
                lines.append(f"| `{rule_id}` | {severity} |")
            lines.append("")
        if not baseline.verified:
            lines += [
                "> **Not verified against a controlling document.**",
                ">",
                f"> {paragraph(baseline.provenance)}",
                "",
            ]
        lines += [
            "<details><summary>Rules selected</summary>",
            "",
            ", ".join(f"`{rule_id}`" for rule_id in sorted(baseline.rules)),
            "",
            "</details>",
            "",
        ]

    unverified = [name for name in names if not baselines[name].verified]
    lines += [
        "## Writing your own",
        "",
        "`src/ipsec_sentinel/assess/baselines/custom.yaml.example` is a template. A baseline",
        "is a rule selection, a set of thresholds and optional severity overrides — and a",
        "`provenance` paragraph, which is not optional in spirit even where the schema",
        "allows it to be thin.",
        "",
        "## What a baseline in this tool is not",
        "",
        "It is an encoding of a public document by this project's authors, not an",
        f"endorsement by the authority that wrote it. {len(unverified)} of the "
        f"{len(names)} baselines here "
        + ("was" if len(unverified) == 1 else "were")
        + " encoded from public description rather than from a verified copy — "
        + ", ".join(f"`{name}`" for name in unverified)
        + " — because the controlling documents are not freely redistributable.",
        "",
        "Nobody has accredited this tool, and a passing grade is evidence for an",
        "assessment rather than a certification. [LIMITATIONS.md](LIMITATIONS.md) is",
        "explicit about that.",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=DESTINATION)
    arguments = parser.parse_args(argv)

    rendered = render_baselines_document()
    if arguments.check:
        current = arguments.output.read_text() if arguments.output.exists() else ""
        if current != rendered:
            print(f"{arguments.output} is stale; run scripts/generate_baselines_doc.py")
            return 1
        print(f"{arguments.output} is current")
        return 0

    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(rendered)
    print(f"wrote {arguments.output} ({len(load_baselines())} baselines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
