"""Generate ``docs/RULES.md`` from the rule registry.

Hand-written rule tables are wrong within a week. This one is generated from the same
registry the assessment runs, and ``tests/unit/test_documentation.py`` regenerates it and
compares — so a rule added without regenerating fails the build rather than surfacing as a
finding nobody can look up.

Run it with::

    python -m scripts.generate_rules_doc          # writes docs/RULES.md
    python -m scripts.generate_rules_doc --check  # exits non-zero if it is stale
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path
from typing import TYPE_CHECKING, Final

from ipsec_sentinel.assess.baselines.schema import get_baseline, load_baselines
from ipsec_sentinel.assess.framework import BUILTIN_TAGS
from ipsec_sentinel.assess.rules import default_registry

if TYPE_CHECKING:
    from ipsec_sentinel.assess.framework import Rule

REPO_ROOT: Final = Path(__file__).resolve().parents[1]
DESTINATION: Final = REPO_ROOT / "docs" / "RULES.md"

FAMILIES: Final = {
    "CRY": ("Cryptographic strength", "What was negotiated, judged against the standards."),
    "IKE": ("Key exchange behaviour", "How the exchange was conducted, not what it agreed."),
    "PFS": (
        "Forward secrecy",
        "Whether today's keys protect yesterday's traffic once the long-term secret leaks.",
    ),
    "SA": ("Security association hygiene", "Lifetimes, rekeying, and anti-replay."),
    "ESP": (
        "Coverage",
        "The two findings that say what the capture could *not* establish — ESP without a "
        "negotiation, and a negotiation with no traffic. Both are inventory findings rather "
        "than cryptographic ones, and both exist so a gap is reported instead of scored as a "
        "pass.",
    ),
    "PQC": ("Post-quantum readiness", "Whether this tunnel survives a harvest-now adversary."),
    "OPS": ("Operational disclosure", "What the tunnel tells an observer about the device."),
}


def family_of(rule_id: str) -> str:
    return rule_id.split("-", 1)[0]


def escape(text: str) -> str:
    """Markdown tables break on an unescaped pipe."""
    return text.replace("|", "\\|")


def technique_link(technique: str | None) -> str:
    if not technique:
        return "—"
    return f"[{technique}](https://attack.mitre.org/techniques/{technique.replace('.', '/')}/)"


def selecting_baselines(rule: Rule, published: dict[str, frozenset[str]]) -> str:
    """Which baselines run this rule, from both namespaces.

    A rule carries the *tags* it belongs to; a published baseline selects rules by ID and
    is authoritative over that list. Conflating the two is what made a named baseline
    silently select zero rules in Phase 10, so both are shown.
    """
    tags = sorted(tag for tag in rule.baselines if tag in BUILTIN_TAGS)
    named = sorted(name for name, ids in published.items() if rule.id in ids)
    return ", ".join([*tags, *named]) or "—"


def render_rules_document() -> str:
    registry = default_registry()
    rules = sorted(registry.rules, key=lambda rule: rule.id)
    published = {name: frozenset(get_baseline(name).rules) for name in sorted(load_baselines())}

    by_family: dict[str, list[Rule]] = defaultdict(list)
    for rule in rules:
        by_family[family_of(rule.id)].append(rule)

    severities: dict[str, int] = defaultdict(int)
    for rule in rules:
        severities[str(rule.severity)] += 1

    lines: list[str] = [
        "# Rules",
        "",
        "<!-- Generated by scripts/generate_rules_doc.py. Do not edit by hand: a test",
        "     regenerates this file and fails if it has drifted from the registry. -->",
        "",
        f"**{len(rules)} rules**, every one of them deterministic. A rule reads what was",
        "parsed from cleartext IKE and returns a finding with `confidence = None`, which is",
        "what routes it to Section A of the report. Nothing here is inferred, nothing here",
        "is a model output, and none of it depends on the traffic classifier.",
        "",
        "Each rule cites the standard it is applying. A check that cites nothing is an",
        "opinion, and an opinion does not belong in a compliance document.",
        "",
        "## At a glance",
        "",
        "| Severity | Rules |",
        "|---|---|",
    ]
    for severity in ("critical", "high", "medium", "low", "info"):
        if severities.get(severity):
            lines.append(f"| {severity} | {severities[severity]} |")
    lines += [
        "",
        "## Baselines",
        "",
        "Two namespaces meet here, and they are not interchangeable.",
        "",
        "**Tags** (`default`, `strict`) are written on the rules themselves and select by",
        "membership. **Published baselines** are policy documents that select rules by ID,",
        "and are authoritative over a rule's own tag list — a policy that names a rule runs",
        "it whether or not the rule expected to belong to that policy.",
        "",
        "| Baseline | Authority | Rules selected |",
        "|---|---|---|",
    ]
    for tag in sorted(BUILTIN_TAGS):
        count = len([rule for rule in rules if tag in rule.baselines])
        lines.append(f"| `{tag}` | built-in tag | {count} |")
    for name in published:
        baseline = get_baseline(name)
        lines.append(f"| `{name}` | {escape(baseline.authority)} | {len(published[name])} |")
    lines += [
        "",
        "See [BASELINES.md](BASELINES.md) for what each authority requires and where the",
        "text of each requirement comes from.",
        "",
    ]

    for prefix, (title, blurb) in FAMILIES.items():
        family = by_family.get(prefix)
        if not family:
            continue
        lines += [
            f"## {title}",
            "",
            blurb,
            "",
            "| ID | Finding | Severity | Standard | ATT&CK | Baselines |",
            "|---|---|---|---|---|---|",
        ]
        for rule in family:
            lines.append(
                f"| `{rule.id}` | {escape(rule.title)} | {rule.severity} | "
                f"{escape(rule.standard_ref)} | {technique_link(rule.attack_technique)} | "
                f"{escape(selecting_baselines(rule, published))} |"
            )
        lines.append("")

    undocumented = sorted(set(by_family) - set(FAMILIES))
    if undocumented:
        lines += [
            "## Uncategorised",
            "",
            "These rule families have no description in `scripts/generate_rules_doc.py`.",
            "",
            "| ID | Finding | Severity | Standard | ATT&CK | Baselines |",
            "|---|---|---|---|---|---|",
        ]
        for prefix in undocumented:
            for rule in by_family[prefix]:
                lines.append(
                    f"| `{rule.id}` | {escape(rule.title)} | {rule.severity} | "
                    f"{escape(rule.standard_ref)} | {technique_link(rule.attack_technique)} | "
                    f"{escape(selecting_baselines(rule, published))} |"
                )
        lines.append("")

    lines += [
        "## What a rule cannot do",
        "",
        "A rule sees one tunnel's negotiated parameters. It does not see what the device is",
        '*capable* of, which is the difference between "this tunnel uses 3DES" and "this',
        'device supports only 3DES" — the first is a fact, the second is a guess, and this',
        "tool only makes the first. [LIMITATIONS.md](LIMITATIONS.md) is explicit about the",
        "rest.",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the published document is stale, writing nothing",
    )
    parser.add_argument("--output", type=Path, default=DESTINATION)
    arguments = parser.parse_args(argv)

    rendered = render_rules_document()
    if arguments.check:
        current = arguments.output.read_text() if arguments.output.exists() else ""
        if current != rendered:
            print(f"{arguments.output} is stale; run scripts/generate_rules_doc.py")
            return 1
        print(f"{arguments.output} is current")
        return 0

    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(rendered)
    print(f"wrote {arguments.output} ({len(default_registry().rules)} rules)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
